plugins {
    alias(libs.plugins.android.library)
}
apply from: "$rootDir/gradle/solar-android-library.gradle"
android {
    namespace 'com.solar.launcher.feature.home'
}
dependencies {
    api project(':core:contracts')
    implementation project(':core:library')
    implementation project(':feature:podcasts')
    testImplementation libs.junit
}
